USERNAME: api_user
PASSWORD: api_user_password
API_PORT: 8728
LISTEN_PORT: 59191
PING_ADDRESSES: '1.1.1.1, 8.8.8.8, 77.88.8.8, ya.ru'

routers:
  ExampleNameRouter1: 192.168.100.1
  ExampleNameRouter2: 192.168.50.1
